- name: Install Apache
  hosts: all
  vars:
  tasks:
    - name: Upgrade installed apt packages
      apt:
        upgrade: dist
      register: upgrade
      retries: 15
      delay: 5
    - name: Check if a reboot is needed for Debian-based systems
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: Reboot the server if needed
      reboot:
        msg: "Reboot initiated by Ansible because of reboot required file."
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when: reboot_required.stat.exists